add_rules("mode.debug", "mode.release")

-- 新建龙芯工具链
toolchain("loongarch64_gnu")
    set_kind("standalone")
    -- 工具链根目录和 bin 目录
    set_sdkdir("/home/zhewana/LoonArch_Workspace/loongson-gnu-toolchain-8.3-x86_64-loongarch64-linux-gnu-rc1.6")

target("odidRecver")
    set_kind("binary")
    add_files("./*.c")
    add_files("./*.cpp")
    remove_files("./rid_capture.c")
    set_toolchains("loongarch64_gnu")
    set_plat("linux")
    set_arch("loongarch64")
    add_links("rt","pthread")
    add_deps("rid_capture")

target("hostTest")
    set_kind("binary")
    add_files("./*.c")
    add_files("./*.cpp")
    set_plat("linux")
    set_arch("x86_64")

target("rid_capture")
    set_kind("binary")
    add_files("./rid_capture/*.c")
    add_files("./opendroneid.c")
    set_toolchains("loongarch64_gnu")
    set_plat("linux")
    set_arch("loongarch64")
    add_includedirs("/usr/local/libpcap_loongarch/include")
    add_linkdirs("/usr/local/libpcap_loongarch/lib")
    add_ldflags("-static", {force = true})
    add_links("pcap")
    add_links("rt")
    add_defines("__USING_POSIX_MSGQUEUE")

-----------------------------------------------------------------------------------

target("tx")
    set_kind("binary")
    add_files("./test/tx.c")
    set_plat("linux")
    set_arch("x86_64")
    add_links("rt")

target("rx")
    set_kind("binary")
    add_files("./test/rx.cpp")
    set_plat("linux")
    set_arch("x86_64")
    add_links("rt")
